version: '3.5'

services:
  database:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
