version: "3.5"

services:
  database:
    container_name: mongo
    image: "mongo"    
    restart: always
    ports:
      - "27017:27017"
    networks:
      - proxy

networks:
  proxy:
    driver: bridge

