version: "3.5"

services:
  database:
    container_name: mongo
    image: "mongo"    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    networks:
      - proxy

networks:
  proxy:
    driver: bridge

