version: '3.5'

services:

  database:
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${PWD}/volume_data:/var/lib/mysql
