version: '3'

services:

  database:
    container_name: mariadb
    image: mariadb:10.1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste
      MYSQL_USER: teste
      MYSQL_PASSWORD: root
